language: erlang
install:
- sudo apt-get install luarocks
- sudo luarocks install luafilesystem
- sudo luarocks install busted
env:
  global:
  - secure: "QwJeGrwau1Ha8ggLZ0yCC/SFfJERb+GfDfCXfw+QMkQj7gjEyKdGA+bCEjT7\nF99An3T6D7RZ9U3xwRN4cN3c5RVD59UfkN+GB+rRTT3zlAnYB48qIWmJ9EGb\nwLIh/6+18PnFOmdyC89K4sZyS5JSrJKhrBlenRoPpLwljGmlVuA="
  - secure: "PzXyPtSW0SN2stk1Hpy83wtF2p5Xhwr5u27MCczyK4FAzb8K64oZWGIrZwpO\n3557w5b3zMKR9jFa8adTsirQmKOIBQrcHbYzNN6+qNmTkLgbdWQBM9UiLrFH\nU7YBTjz+4oxIMLq/ik9QgMhXV1fL2AzC1SryNTpgST0LL8EAsNc="
  - secure: "YVRKVqhiV0uvKPvcdA65ZBtdznQsa5iwam1ZFkMoInHvVEEBORitO/gV4URC\nMPl/fvrvITpuxN3qg/4uYUcLNClByq6i8jpAIOAT1kCaVsHFZV4rVs2sEF12\nOiqQmoEdNYoNu2K1+r+150baSJN1ie7MH6Tj45ZIUGnyxULrJ1g="
  - secure: "ZPDXiri+flw95v/k+65AT23AqUo4ObvffGWqz7EszvTR/znyX1qtIghkDe8K\n5Xa21TExaOT2TyubTc6Cue3M59IRTRH+ja1tnRSfv+iGLhdkWidHwhQMR/do\nnRj6V4xAHXqDqUb1fhwnxZjHf+f2dRyP0Xje6rQEBKLP19hLd4M="
  - secure: "WpxonUYF+pSEXp3skPvHcceaaBAdxR7uHskmcOBQq9tVA9CWiPpdi7f/FGlG\nxZoazOqlQRPF/s1IR69YEgyaOJZZS6jP/4uV6u/ODP/n5oA0aosRgU3gpJom\nlHrK/xvULPDZCrbIInUtIAJS0hZuoqRPBzVazXPUoArVWBe1p8Y="
  - secure: "BRYYWlc0Np9ijPmTRzrKd/NE2pv0xWNTAWPHD3oRWZe/cDOQ/394Pr0uz95c\nRXS/mtcz33/uM8bhnYxw4ToijlGNacgCUxDdnQK20mDOjytJBNW135frR4hQ\nIp1VhWLRYIh9g8YuaPyhUZcnqcCzqjw21eRlXmGq/acWlth5+w0="
script: make deploy

