language: erlang
install:
- sudo apt-get install luarocks
- sudo luarocks install luafilesystem
- sudo luarocks install busted
env:
  global:
  - secure: "gIU+AVn8Cgk1estcjEmD++DFacTsoCiwSJWhS24PB9AB6qSaFwaSdZg1ePkt\nlRhi25q9OirnuZ3SvUUgF/mKKjggLEeowMrKQqEjzL9Vyw3Rvb2++A6g9tAL\nFfb9hOKuwuj1LKdnLf0e0R3C52nrsY0BK20W0iiNEEt9zIVUkHo="
script: make deploy
